# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# test

title: Max Graf
email: max.graf@qmul.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  This is my personal website yadda yadda.
author: Max Graf
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github: maxgraf96
instagram: _maxgraf
spotify: asdf
facebook: maxgraf1996
linkedin: max-graf-3265171a9
twitter: maxgraf__
youtube: UC8B_BlQEDOehnXvGmYPjPDQ

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-redirect-from

header_pages:
  - _pages/music.md
  - _pages/research.md
  - _pages/code.md
  - _pages/about.md

include:
  - _pages


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .gitignore
#  - Gemfile
#  - Gemfile.lock
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
